---
title: "Library AI Trials"
description: "Building, testing, and questioning AI in libraries."
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

<p>The site is a window into work at Stanford Libraries to build capacity in AI while experimenting with applications of AI on library materials and in library processes. We approach building capacity as a cross-library effort. While an essential part of the effort is giving developers an opportunity to get their hands on new tools and understand new ways of working, it is also an effort to familiarize people from all parts of the library with the potential of AI so that they can identify useful applications of the technology, help shape the projects, assess outcomes (at every step) and bring domain expertise to the challenges that arise.</p>
<p>The Stanford Libraries Steering Group formed in 2020 to shape and guide the effort. The group produced a document, <a href="https://github.com/sul-dlss-labs/ai-projects/raw/main/docs/Stanford%20Libraries%20AI%20Guiding%20Values.pdf">Stanford Libraries AI Guiding Values</a>, to explicitly address the ways we think the ethos of the library needs to be reflected in the ways we use this technology.</p>
<p>The Steering Group also compiled a set of <a href="https://github.com/sul-dlss-labs/ai-projects/raw/main/docs/Stanford%20Libraries%20AI%20Project%20Guidelines.pdf">Project Development Guidelines</a> for library-based AI projects, drawing upon the guiding values as well as the lessons learned while developing the experimental projects described below.</p>
<div class="section" id="current-active">
<h2>CURRENT - ACTIVE</h2>
<div class="section" id="spoc-species-occurrences">
<h3>SPOC (Species Occurrences)</h3>
<p><a class="reference external" href="https://sul-dlss-labs.github.io/spoc/">Project Book</a> - Data, models, and documentation of the project</p>
<p><a class="reference external" href="https://github.com/sul-dlss-labs/spoc">Github Repository</a> - Code repository and project communications</p>
<p>Observations of marine plants and animals are “hidden” in the text of undergraduate student research papers (Paper &gt; TIFF &gt; OCR &gt; plain text). These historical observations are important historical markers for studies of biodiversity and the effects of climate change on species. The goal of this project is to extract species occurrences (genus-species, place, time) from student papers held in libraries along the western coast of the U.S., verify those observations, and contribute them to the <a class="reference external" href="https://www.gbif.org/">Global Biodiversity Information Facilty (GBIF)</a>.</p>
</div>
</div>
<div class="section" id="previous-projects">
<h2>PREVIOUS PROJECTS</h2>
<div class="section" id="electronic-theses-and-dissertations">
<h3>Electronic Theses and Dissertations</h3>
<p>This project was our first dive into how machine learning and natural language processing might help us automate the assignment of subject headings from the <a class="reference external" href="https://www.oclc.org/research/areas/data-science/fast.html">FAST (Faceted Application of Subject Terminology)</a> vocabulary to ETDs.</p>
<p><strong>Objective</strong>: To become familiar with the data, experiment with methods, and determine whether we can successfully automate or semi-automate FAST subject headings for ETDs.</p>
<p><strong>Outcomes:</strong></p>
<ul class="simple">
<li><p><a class="reference external" href="https://github.com/sul-dlss-labs/druid_2_text">druid_2_text</a> (to retrieve pdf from our repository and convert to txt for pre-processing)</p></li>
<li><p><a class="reference external" href="https://github.com/sul-dlss-labs/etd_structure_classifier">Document Structure Classifier</a> (to extract bibliographies)</p></li>
<li><p><a class="reference external" href="https://biology-fast-etds.herokuapp.com/">Biology ETDs FAST tagging app</a></p></li>
<li><p><a class="reference external" href="https://etd-abstract-similarity.herokuapp.com/">Abstract Similarity/clustering app</a></p></li>
</ul>